#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       ksh, or zsh, then change the shebang line above to use that shell.
#
#   (2) The Gradle wrapper script does not work in some shells.
#       Try running this script with bash, ksh, or zsh.
#
#   (3) When using the Gradle build and you get an "Illegal reflective access" warning, this is caused by the
#       Gradle daemon not being able to access classes in modules.
#       This is an expected behavior and is safely ignored.
#
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" && pwd -P)

FIND_JAVA_EXE() {
  local java_exe
  if [ -n "$JAVA_HOME" ]; then
    java_exe="$JAVA_HOME"/bin/java
    if [ ! -x "$java_exe" ]; then
      echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
      return 1
    fi
  else
    java_exe=$(command -v java 2>/dev/null) || {
      echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
      return 1
    }
  fi
  echo "$java_exe"
}

JAVA_EXE=$(FIND_JAVA_EXE) || exit 1

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
export CLASSPATH

exec "$JAVA_EXE" \
  -Dorg.gradle.appname="$APP_NAME" \
  -Dorg.gradle.wrapper.properties="$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
  -cp "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
