#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       ksh, or zsh, then change the shebang line above to use that shell.
#
#   (2) The Gradle wrapper script does not work in some shells.
#       Try running this script with bash, ksh, or zsh.
#
#   (3) When using the Gradle build and you get an "Illegal reflective access" warning, this is caused by the
#       Gradle daemon not being able to access classes in modules.
#       This is an expected behavior and is safely ignored.
#
##############################################################################

exec "$0.bat" "$@"
