[versions]
agp = "9.1.1"
kotlin = "2.2.10"
gradle = "9.3.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
material = { group = "com.google.android.material", name = "material", version = "1.11.0" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version = "1.11.0" }
